### PR TITLE
Really fix Coinbase

### PR DESCRIPTION
**Pull request by vonagam**
Complete rewrite of Coinbase from scratch.

Previous fixes was sufficient only for showing '/account-info' page.
We hadn't yet started to use exchange for processing, when i did those fixes.
When we finally started to process transactions, it became clear that Coinbase API wrapper didn't work at all. There still were many errors. Too many.

That's why i rewrote wrapper.
I rewrote it with formatting i use ( similar to three.js ).
It can be easily changed.

### CODE REVIEW

**Comment by jtcoyle** [comment]
I first would like to say thank you for all those who are working on this project.  I cannot wait until I can get this to work.  I am trying to setup a connection to my coinbase exchange account.  When do you expect this code to be merged in?  I at a stand still until I can get this connector to work.

**Comment by thallium205** [comment]
Thanks for this pull request.  The existing Coinbase implementation was not written by Romit but by another contributor so thank you for your patience.

Before we can merge, I need to ask if you were able to find a way of overcoming the Coinbase limitation of loading bitcoin into the exchange account directly from the network.  The last time we reviewed their docs, you were able to generate a bitcoin deposit address and load bitcoin into the wallet, but there was no way of transferring it from the wallet into the exchange from their API.  Additionally, there is no way to directly load the exchange account with bitcoin. 

Is this still the case?

**Comment by jtcoyle** [comment]
From my experience with coinbase exchange, they provide a transfer option on the exchange api.  Please see this page https://docs.exchange.coinbase.com/#transfer-funds

**Comment by thallium205** [comment]
Yep, that definitely appears to be new.  Exciting!  Just so I am not losing my mind, I dug up an old support ticket another contributor had with them when trying to implement this:

image

After the bitcoin arrives at the exchange account, the connector will initiate a sell on the exchange to lock in the rate.  

I would suggest, in this pull request, this /transfers endpoint first be used to transfer the newly deposited bitcoin into the exchange account, and then execute the sell.  All of this can be achieved within the `Coinbase.prototype.sell` method.  Once bitcoin is transferred, then place the sell order.  Under the current implementation, I'm afraid the exchange account will run out of bitcoin eventually as it is not getting replenished from the automatic forwarding of coins from Romit.

**Comment by vonagam** [comment]
"I would suggest, in this pull request, this /transfers endpoint first be used to transfer the newly deposited bitcoin into the exchange account, and then execute the sell. All of this can be achieved within the Coinbase.prototype.sell method."

That's exactly what happens in this implementation.
/transfers endpoint is hit inside sell method:
https://github.com/vonagam/robocoin-connector/blob/1629344ee5cbdcdf194893eeb56f602c95113ee0/apis/exchanges/Coinbase.js#L154

**Comment by jtcoyle** [comment]
Vonagam and thallium205,

let me see if If I understand how the robocoin-connector is supposed to work with Coinbase exchange api.  

Customer selling Bitcoints
1.  A customer sells bitcoins at a kiosk
2.  bitcoins are deposited into the Contributor's Romit Wallet account
3.  bitcoins are forwarded to the Contributor's coinbase wallet using the Romit connector forwarding bitcoin address
4.  bitcoins are transferred from the coinbase wallet into the Coinbase exchange account
5.  a sell order is issued for the bitcoins
6.  fiat is left in coinbase account or transferred to the coinbase wallet?

Customer buying bitcoins
1.  fiat is deposited into a kiosk
2.  bitcoins are sent from the Contributors Romit Wallet account to the customer's provided bitcoin wallet address
3.  fiat is transferred from the Contributors coinbase wallet to the coinbase exchange account
4.  a buy order is issued for bitcoins
5.  bitcoins are transferred from the coinbase exchange to the coinbase wallet
6.  bitcoins are then set from the coinbase account to the Contributor's Romit Wallet to replenish the sold bitcoins

One point to consider:  The coinbase exchange api also provides a way to get a bitcoin/fiat balance of the contributors exchange account.  If the exchange account has sufficient bitcoins or fiat then there is no need to transfer from the coinbase wallet into the coinbase exchange to place a buy or sell order.  Just use the excising funds in the Contributors coinbase exchange account to place the buy or sell order.  There could be an option that says first use coinbase exchange funds if they exist and if they do not perform the transfer from the coinbase wallet.

Please correct me if I am wrong.

**Comment by thallium205** [comment]
@vonagam Nice, I didn't see that because I was looking for the word "transfer".  This looks good.  @jtcoyle Everything you describe is correct.

**Comment by thallium205** [comment]
@darinrogers - Would you review this?

**Comment by jtcoyle** [comment]
if I can get a working rocobcoin net sdk that I can test with I would be more than happy to assist with testing.  I have a verified coinbase account.  Can you provide a working  sdk?  I would also like to see a non kiosk sdk.  What I mean is, I would like to have a full kiosk sdk that I can run on a desktop, tablet or mobile device without needing kiosk hardware (Bill dispenser/bill collector, plan scanner, etc).  This would be similar to your robocoin web browser cashier app but a full kiosk sdk.  I am running on a Windows 7 platform.  I want to test using the sdk before purchasing a kiosk

**Comment by thallium205** [comment]
@jtcoyle Have you investigated https://github.com/RoboCoin/robocoin-sdk-net-sample ?

**Comment by jtcoyle** [comment]
yes, i have downloaded the code and compiled it using Microsoft Visual Studio 2012 but could not get the app to run correctly.  I will try to compile the code again and let you know if I have any problems.

**Comment by thallium205** [comment]
Great.  Feel free to open up an issue on that project if you continue having issues.

**Comment by jtcoyle** [comment]
I was able to compile the sdk.  After entering the Machine's API key and secrete, I get the following errors. "Error getting BTC price" and then Error Kios info:  Access denied"  

I am using the api key and secrete found under the Operator Wallet settings.  Is this the correct API?

**Comment by thallium205** [comment]
Please create a separate issue in that project.  Thanks.

**Comment by vonagam** [comment]
@jtcoyle about current flow.

Everything right except there is no 3 step in buying process. ( "fiat is transferred from the coinbase wallet to the coinbase exchange" )

We assume that a person store fiat on the coinbase exchange and btc on his coinbase wallet.

We store btc in a wallet, cause it is used for transfers.
We store usd on the exchange, cause there is no fiat wallets in coinbase ( if i remember right ).

**Comment by jtcoyle** [comment]
These are the default wallets that gets created on Coinbase when you setup an account.  There is a fiat wallet.

image

**Comment by vonagam** [comment]
Hm... so we have those usd wallets.

In this case, yes, we can add transfers between usd wallets and exchange account to the flow.

What needed to be done for this:
- change in Coinbase.json settings: adding options for a usd wallet.
- adding deposit to and withdraw from the usd wallet to buy and sell methods respectively.
- replacing an exchange with a usd wallet as a source for fiat balance in the getBalance method.

Pros:
- just some aesthetics: adding some symmetry to the flow of buy, sell, getBalance methods.

Cons:
- performance: additional request for every sell and buy action.
- minor inconvenience: if you have set up connector, changing settings file, will add need to manually  clear settings.

Do i miss some pros?

**Comment by jtcoyle** [comment]
@vonagam

I believe you nailed the pros.

I disagree that performance would be an issue.  The few extra steps would not be detected by a customer.  Transfers are instant between coinbase and exchange.

Some testing would need to be done to see how the getBalance methods might effect  performance.  If there is any performance hit, i do not believe it would be detected by a human.  Think about a credit card transaction.  The credit card authorization with the processor takes a few seconds to receive an cc auth # or a declined message.

I am not a coder but i work in Point of Sale software  development and support and would be more than willing to assist with software design and testing robocoin-connector.

I am interested in this project because i am very interested in  deploying and managing BTMs

**Comment by vonagam** [comment]
No, getBalance will not have any performance changes, cause there are 2 requests and there will be 2 requests. Just one of them will be not to the exchange, but to a different wallet.

What will change is sell and buys method. Cause now, there will be 3 requests instead of 2 for each operation.

And this adding of third wallet to the flow do not help to anything.

But if after the review the owner will decide, that it's better to add this wallet, i'll do it.

**Comment by jtcoyle** [comment]
I always like more features than less.  Having said that, it is not a deal breaker if we do not add the 2nd fiat wallet.  Options and features can always be added later.  Lets just get this connector working with coinbase.

**Comment by jtcoyle** [comment]
Is there a estimated time frame when this Pull request will be merged in?

**Comment by jtcoyle** [comment]
It looks like coinbase has added "Instant Exchange"  Does this help what we are trying to accomplish here with the coinbase exchange robocoin-connector?

https://support.coinbase.com/customer/portal/articles/2021569-what-is-instant-exchange-

**Comment by thallium205** [comment]
Please keep in mind that there is no performance hit to the end user as all Romit operations occur independently of the connector.  The exchange could go completely offline and so long as there is sufficient float in the operator wallet, it will still transact normally.  When the exchange comes back online, it will merely adjust accordingly.  

Let's wait and see if the proposed USD wallet integration is something that is needed.  Let's get this merged.

**Pull request merged**
